--- 
phases: 
  build: 
    commands: 
      - echo Build started `date`
      - docker build -t arena:latest .
      - docker tag arena:latest 880644200418.dkr.ecr.us-east-1.amazonaws.com/arena:latest
  post_build:
    commands: 
      - echo Build finished `date`
      - docker push 880644200418.dkr.ecr.us-east-1.amazonaws.com/arena:latest
      - printf '[{\"name\":\"arena\",\"imageUri\":\"880644200418.dkr.ecr.us-east-1.amazonaws.com/hazelmollusk/arena:latest\"}]' > imagedefinitions.json
      - cat imagedefinitions.json
  pre_build: 
    commands: 
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password | docker login --username AWS --password-stdin 880644200418.dkr.ecr.us-east-1.amazonaws.com
artifacts:
  files: imagedefinitions.json
version: 0.2
