--- 
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t hazelmollusk/arena ."
      - "docker tag hazelmollusk/arena hazelmollusk/arena"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push hazelmollusk/arena:latest"
  pre_build: 
    commands: 
      - "echo Logging in to Docker Hub..."
      - "docker login --username=\"hazelmollusk\" --password=\"HailEris523!\""
version: 0.1