--- 
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t arena ."
      - "docker tag arena hazelmollusk/arena"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push hazelmollusk/arena:latest"
      - "printf '[{\"name\":\"arena\",\"imageUri\":\"hazelmollusk/arena\"}]' > imagedefinitions.json"
      - "cat imagedefinitions.json"
  pre_build: 
    commands: 
      - "echo Logging in to Docker Hub..."
      - "docker login --username=\"hazelmollusk\" --password=\"HailEris523!\""
artifacts:
  files: imagedefinitions.json
version: 0.1
