# Generated by Django 3.2.8 on 2021-10-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creaturebase',
            old_name='move',
            new_name='moves',
        ),
        migrations.RemoveField(
            model_name='creature',
            name='move',
        ),
        migrations.AddField(
            model_name='creature',
            name='moves',
            field=models.IntegerField(default=0),
        ),
    ]
