# Generated by Django 4.0rc1 on 2021-12-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spellbase',
            name='level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
