# Generated by Django 3.2.5 on 2021-08-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='size',
            field=models.PositiveSmallIntegerField(default=20),
        ),
    ]
