# Generated by Django 4.0rc1 on 2021-12-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_creature_damage_spellbase_target_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='cast',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='spellbase',
            name='target_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Summon'), (1, 'Adjacent'), (2, 'LOS'), (3, 'Creature'), (4, 'Any'), (5, 'None')], default=0),
        ),
    ]
