# Generated by Django 3.2.8 on 2021-10-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20211007_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creature',
            name='exp',
        ),
        migrations.RemoveField(
            model_name='creaturebase',
            name='exp',
        ),
        migrations.RemoveField(
            model_name='spellbase',
            name='exp',
        ),
        migrations.AddField(
            model_name='creaturebase',
            name='spells',
            field=models.ManyToManyField(blank=True, null=True, to='game.SpellBase'),
        ),
    ]
