# Generated by Django 3.2.8 on 2021-10-09 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20211009_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spellbase',
            old_name='summon_creature',
            new_name='summons',
        ),
        migrations.RemoveField(
            model_name='spellbase',
            name='summon',
        ),
    ]
