# Generated by Django 3.2.6 on 2021-09-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20210908_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='burnt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cell',
            name='tile',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Grass'), (1, 'Plain')], default=0),
            preserve_default=False,
        ),
    ]
