# Generated by Django 4.0rc1 on 2021-12-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_spellbase_effect'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='alive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='creature',
            name='hp',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='creaturebase',
            name='alignment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='spellbase',
            name='effect',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Summon'), (1, 'Fireball')], default=0),
        ),
    ]
