# Generated by Django 3.2.6 on 2021-09-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20210917_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='players',
            new_name='max_players',
        ),
        migrations.AlterField(
            model_name='creature',
            name='x',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='creature',
            name='y',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
