# Generated by Django 4.0rc1 on 2021-12-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_gameplayer_alive_alter_creature_hp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='align',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='spellbase',
            name='effect',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Summon'), (1, 'Fireball'), (2, 'Strength')], default=0),
        ),
    ]
