# Generated by Django 3.2.8 on 2021-10-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20211010_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='alive',
            field=models.BooleanField(default=True),
        ),
    ]
