# Generated by Django 4.0rc1 on 2021-12-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_creature_align_alter_spellbase_effect'),
    ]

    operations = [
        migrations.AddField(
            model_name='spellbase',
            name='repeat',
            field=models.BooleanField(default=False),
        ),
    ]
