# Generated by Django 4.0rc1 on 2021-12-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_creaturebase_summon_message_creaturebase_summon_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='hp',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='creature',
            name='moves',
            field=models.SmallIntegerField(default=0),
        ),
    ]
