# Generated by Django 4.0rc1 on 2021-12-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_remove_creaturebase_summon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='spellbase',
            name='ranged',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='spellbase',
            name='effect',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Summon'), (1, 'Fireball'), (2, 'Strength'), (3, 'Arrows')], default=0),
        ),
        migrations.AlterField(
            model_name='spellbase',
            name='target_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Summon'), (1, 'Adjacent'), (2, 'LOS'), (3, 'Creature'), (4, 'Any'), (5, 'Ranged'), (6, 'None')], default=0),
        ),
    ]
