# Generated by Django 4.0rc1 on 2021-12-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_spellbase_ranged_alter_spellbase_effect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spellbase',
            name='wizard',
            field=models.BooleanField(default=True),
        ),
    ]
