# Generated by Django 4.0rc1 on 2021-12-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_spellbase_wizard'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='flying',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creaturebase',
            name='flying',
            field=models.BooleanField(default=False),
        ),
    ]
