# Generated by Django 4.0rc1 on 2021-12-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_creature_magical_creaturebase_magical'),
    ]

    operations = [
        migrations.AddField(
            model_name='creaturebase',
            name='undead',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='spellbase',
            name='effect',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Summon'), (1, 'Fireball'), (2, 'Strength'), (3, 'Arrows'), (4, 'Grass'), (5, 'Mirkwood'), (6, '')], default=0),
        ),
    ]
