# Generated by Django 4.0rc1 on 2021-12-26 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_creaturebase_undead_alter_spellbase_effect'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creaturebase',
            old_name='hp',
            new_name='defend',
        ),
    ]
