# Generated by Django 4.0rc1 on 2021-12-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_rename_hp_creaturebase_defend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creature',
            old_name='damage',
            new_name='attack',
        ),
        migrations.RenameField(
            model_name='creature',
            old_name='hp',
            new_name='defend',
        ),
        migrations.RenameField(
            model_name='creaturebase',
            old_name='damage',
            new_name='attack',
        ),
        migrations.AlterField(
            model_name='spellbase',
            name='effect',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Summon'), (1, 'Fireball'), (2, 'Strength'), (3, 'Arrows'), (4, 'Grass'), (5, 'Mirkwood'), (6, 'Summon')], default=0),
        ),
    ]
