# Generated by Django 4.0rc1 on 2021-12-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_rename_damage_creature_attack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spellbase',
            name='success_msg',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
