# Generated by Django 4.0rc1 on 2021-12-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_spellbase_success_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='undead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spellbase',
            name='failure_msg',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
